name: voila
channels:
  - conda-forge
dependencies:
  - python
  - ipykernel
  - pip
  - ultralytics
  - pillow
  - python-dotenv
  - opencv
  - jupyterlab_widgets
  - voila
  - ipywidgets

  - pip:
    - voila-topbar
