name: voila
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - ipywidgets
  - ipykernel
  - pip
  - ultralytics=8.0.186
  - pillow
  - python-dotenv
  - opencv

  - pip:
    - voila==0.5.0
    - voila-topbar==0.1.1
