name: voila
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - ipykernel
  - pip
  - ultralytics
  - pillow
  - python-dotenv
  - opencv

  - pip:
    - voila==0.5.0
    - voila-topbar==0.1.1
